apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wazuh
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chzgustavo/wazuh-k8s.git
    targetRevision: HEAD
    path: envs/local-env
  destination:
    server: https://kubernetes.default.svc
    namespace: wazuh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
