apiVersion: v1
kind: Service
metadata:
  name: dashboard
  namespace: wazuh
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: indexer
  namespace: wazuh
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh
  namespace: wazuh
spec:
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: wazuh-workers
  namespace: wazuh
spec:
  type: NodePort
